---
name: kgoldrunner
version: 17.08.1
summary: A game of action and puzzle-solving
description: |-
    KGoldrunner is an action game where the hero runs through a maze, climbs stairs, dig holes and dodges enemies in order to collect all the gold nuggets and escape to the next level. Your enemies are also after the gold. Worse still, they are after you!.

    Features:

    - Themeable
    - Hundreds of levels
    - Level-editor
    - Two modes for the enemies: classical and KGoldrunner-mode, in KGoldrunner-mode they are more intelligent, in the classical mode it is easier to fool them
    - Very very difficult levels
    - Keyboard or mouse control
    - Savable games
confinement: strict
grade: stable
apps:
    kgoldrunner:
        command: kf5-launch kgoldrunner
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kgoldrunner
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kgoldrunner:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libkf5kdegames-dev
        - libphonon4qt5-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kgoldrunner-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
